version: '3.0'
services:
    php:
        build:
            context: ./dockerfiles/php/
            args:
                - user=${USER}
        ports:
            - "8080:80" #nginx
        volumes:
            - ./app/api.anatroc/:/usr/share/nginx/html
        networks:
            static-network:
                ipv4_address: 172.40.0.10

    node:
        build:
            context: ./dockerfiles/node
        ports:
            - "3000:3000"
        volumes:
            - ./app/devFront/:/app
        command: "tail -f /dev/null"
        networks:
            static-network:
                ipv4_address: 172.40.0.11

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.40.0.0/24

