app:
    resource: '@AppBundle/Controller/'
    type: annotation

meteo:
    type:     rest
    resource: AppBundle\Controller\MeteoController

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

